// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Project;

import java.sql.Date;

/************************************************************/
/**
 * 
 */
public class Appointment {
	/**
	 * 
	 */
	public int apt_no;
	/**
	 * 
	 */
	public Date apt_date;
	/**
	 * 
	 */
	public boolean apt_status;
	/**
	 * 
	 */
	public Notification notification;

	/**
	 * 
	 */
	public void cancelApt() {
	}

	/**
	 * 
	 */
	public void addApt() {
	}

	/**
	 * 
	 */
	public void changeApt() {
	}
}
