// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Project;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String number;
}
