// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Project;

/************************************************************/
/**
 * 
 */
public class Notification {
	/**
	 * 
	 */
	public String message;

	/**
	 * 
	 */
	public void emailText() {
	}

	/**
	 * 
	 */
	public void smsText() {
	}
}
