// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Project;

/************************************************************/
/**
 * 
 */
public class service_provider {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String type;
}
